### ISSUE TITLE
Improve Flow Card Arguments

### ISSUE THREAD

**Issue by MadMonkey87** [athombv/apps-sdk-issues#194] opened 2021-04-16 16:02 UTC
When using a bit more complex flow cards I often struggle a bit how they are handled by Homey. You can find some examples and the end.

Here are some ideas how this could be improved:

 - FormattedTitle: currently needs include all arguments which is understandable as this is used in Homey Web which represents the entire card. This is fine for simple cards but some require more arguments. Example: Rest Call, Combined Zigbee Command. Suggestion: it should be possible that the FormattedTitle does not need to cover all arguments. Homey Web could be adapted s.t a detail view is shown for cards like this where all arguments can be entered. Or in other words: splitting the actual configuration of the card and it's title shown in the flows. For example the formated title would be 'Perform GET Request to xyz' but opening the card then shows more arguments such as headers, certificates, authorization and so on
 - Text input that can be empty.
 - Validation: often the user cannot save the flow card because some arguments are not valid, but as there is no feedback at all it is impossible for the user to see what's wrong. There are a lot of possible approaches, less and more complex ones. An easy one would be that we can provide regex expressions to every field. And even better one would be that we can register a validator on the flow card instance that can return global validations that are not related to a specific field and field related validation messages.
 - Complex "argument relationships": Complexer flow cards might required so dependencies across fields. For example a Http Request would have a body field only if the method is a post or a put. I am fully aware that this one might be tricky;)

Some of these suggested improvements should be really easy to provide and would offer a great improvement (in my opinion). Others are more a suggestion for the future and are maybe a bit more targeted for a more advanced/professional usage of Homey, maybe one day there will be something like Homey for Business or so, who knows.

Any ideas on my suggestions?

![Screenshot_20210416-175904_Homey](https://user-images.githubusercontent.com/29612400/115052127-e01ead80-9edd-11eb-9706-908e89b7828d.png)
![Screenshot_20210416-175745_Homey](https://user-images.githubusercontent.com/29612400/115052130-e0b74400-9edd-11eb-9acc-b14c17f016b1.jpg)
![Screenshot_20210416-175809_Homey](https://user-images.githubusercontent.com/29612400/115052131-e0b74400-9edd-11eb-85ad-4e5bdee74975.png)
![Screenshot_20210416-175916_Homey](https://user-images.githubusercontent.com/29612400/115052132-e14fda80-9edd-11eb-82b1-80225c84a45c.jpg)

**Comment by tjallingt** [comment] 2021-04-19 13:54
Hey, thanks for sharing!

Some of these are, as you mention yourself, some pretty advanced use cases for Flow. I agree we can definitely improve the user experience in those cases.

> FormattedTitle: [...]

Yea in case of the "Make a HTTP request" this is not the best design, however in general we really like the look of the `titleFormatted` Flow cards in the Web App. Usually when this looks bad the Flow card in question is pretty complicated itself and may benefit from being broken up into several cards/steps. The "breaking up" of Flow complex cards may also make it easier for users to use the Flow card (but it can also make cards more complicated to use).

I'd love to see more examples of Flow cards where `titleFormatted` is confusing/overwhelming/complex, based on such examples we can better judge whether the problem is that the Flow card itself is too complicated or whether we need to add the ability to "hide" arguments from the `titleFormatted`.

> Text input that can be empty.

Can you give an example of where you needed this?

> Validation: often the user cannot save the flow card because some arguments are not valid, but as there is no feedback at all it is impossible for the user to see what's wrong. [...]

You mean there is no feedback beyond the basic validation (not empty, within the given range, etc)?
Adding additional flow card validation is an interesting idea, it'd be great if you have some specific/real world examples where you needed more advanced validation.

> Complex "argument relationships": [...]

Yea this would be validation on steroids haha, I think this could be done with the "validator" for a Flow card that you mentioned. However if most Flow cards are simple enough that they wouldn't need this (if the simple validation is good enough) I don't think there are many use cases for this. Or do you think there are simpler Flow cards that could also benefit from this?

I'm closing since its not an issue/bug but feel free to continue the discussion!

**Closed as completed by tjallingt** 2021-04-19 13:54 UTC
Labels: suggestion
