### ISSUE TITLE
SDK2 app works in homey 4.2.0 but not in homey 5.0.0

### ISSUE THREAD

**Issue by nattlip** [athombv/apps-sdk-issues#136] opened 2020-08-22 15:21 UTC
the app plugwise.jilles.com.2 https://github.com/nattlip/com.jilles.plugwisesource.2 crashes soon after starting the app in homey version 5.0.0 r23 . it works on homey 4.2.0

the problem in homey 5.0.0 is that the cirlce driver is invalid. i foiund this with the ecxellent post https://community.athom.com/t/debug-app-code/33516 where you can debug the code on homey so you dont have to makea logging anymore.

**Comment by WeeJeWel** [comment] 2020-08-22 17:20
What exactly is why it crashes? Do you have a crashlog?

**Comment by nattlip** [comment] 2020-08-22 17:31
TypeError: Cannot read property 'length' of undefined
    at MyApp.contains (/app.js:501:31)
    at MyApp.transports (/app.js:457:19)
    at MyApp.TranslateAppliancesToAppDevices (/app.js:431:46)
    at /app.js:309:18
    at Parser.<anonymous> (/node_modules/xml2js/lib/parser.js:303:18)
    at Parser.emit (events.js:311:20)
    at SAXParser.onclosetag (/node_modules/xml2js/lib/parser.js:261:26)
    at emit (/node_modules/xml2js/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/node_modules/xml2js/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/node_modules/xml2js/node_modules/sax/lib/sax.js:889:7)
Emitted 'error' event on Parser instance at:
    at Parser.exports.Parser.Parser.parseString (/node_modules/xml2js/lib/parser.js:326:16)
    at Parser.parseString (/node_modules/xml2js/lib/parser.js:5:59)
    at MyApp.resolveGet (/app.js:291:16)
    at IncomingMessage.<anonymous> (/app.js:231:30)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

app .js 486

  contains(a, obj) {
        try {
        for (var i = 0; i < a.length; i++) {
            if (a[i].data.id === obj.data.id) {
                return true;
            }
        }
        return false;
    }
called from

app.js 481 

the lenght which doesnt exist is from the circle driver i get a invalid driver error at app.js 481   in visual code debug but cant catch it

**Comment by nattlip** [comment] 2020-08-22 17:32
and strange , it looks like the circel driver is initated twice, also in homey 4.2.0

**Comment by nattlip** [comment] 2020-08-22 17:56
![IMG_20200822_195347](https://user-images.githubusercontent.com/7040452/90962587-964a0880-e4b1-11ea-8479-44dca601154d.jpg)

**Comment by tjallingt** [comment] 2020-08-31 11:33
Mhh this seems to be caused by an internal change where we used to ready all drivers before require-ing `app.js` but now we require `app.js`, then ready the drivers and then call `App#onInit()`, I recommend to update your `app.js` to do the following in `onInit()`:

```js
class MyApp extends Homey.App {
  onInit() {
    this.driverCircle = Homey.ManagerDrivers.getDriver('circle');
    this.driverLight = Homey.ManagerDrivers.getDriver('light');
  }
}
```

and now you should be able to use `this.driverCircle` and `this.driverLight` in all places where you now use `driverCircle` and `driverLight`.

Since we did change/break this I'll discuss to see if we can/should fix this in SDK v2.

**Comment by nattlip** [comment] 2020-09-01 17:00
@tjallingt  that works indeeds. now the app is undermy microscope i made a sdk3 version aswel , but there it doesnt work , but this works well but cant be the intention of sdk 3 async and await doesnt work ether
`
onInit() {

` setTimeout(() => {
           this.driverCircle = this.homey.drivers.getDriver('circle')
           this.driverLight = this.homey.drivers.getDriver('light');
       }, 1000);
```

**Comment by tjallingt** [comment] 2020-09-01 17:02
Mhh the setTimeout should definitely not be necessary... There might be a race condition there though, I'll look into it tomorrow!

**Comment by tjallingt** [comment] 2020-09-02 09:25
Ah sorry I got confused, it is correct that SDK v3 behaves differently than SDK v2.
In SDK v3  your apps `onInit` is called before the drivers and devices get created.

The order is:

```
App onInit
Driver onInit
Device onInit
```

The idea is that your driver/devices can always access your app when they are created.

so instead of calling `this.homey.drivers.getDriver('circle')` from your `app.js` you can call your app methods from your `device.js` like this (for example): `this.homey.app.getApplianceForDevice(this)`

**Comment by tjallingt** [comment] 2020-09-02 09:28
`5.0.0-rc27` should have fixed the SDK v2 issue, and the SDK v3 is an intended change so I'll close this issue.
I'll update the SDK v3 docs to make this change to the order of `onInit` a bit clearer 👍 
If you have questions about the SDK v3 behaviour feel free to reach out on Slack (maybe in Dutch?)

**Closed as completed by tjallingt** 2020-09-02 09:28 UTC

**Comment by nattlip** [comment] 2020-10-18 08:05
clear .
