### ISSUE TITLE
Automatic sub capability flow triggers are not working

### ISSUE THREAD

**Issue by AdyRock** [athombv/apps-sdk-issues#207] opened 2021-05-26 08:55 UTC
I have implemented some sub capabilities and added the value changed flow triggers to the json file. However, the flows are not being called when the value changes. here is an example of one of the capabilities and the flow entries:
`"measure_temperature.dewPoint"`

```
    "capabilitiesOptions":
    {
        "measure_temperature.dewPoint":
        {
            "title":
            {
                "en": "Dew point",
                "nl": "Dauwpunt",
                "de": "Taupunkt"
            },
            "decimals": 1
        }
    },
```

```
    "triggers": [
        {
        {
            "id": "measure_temperature.dewPoint_changed",
            "title": {
                "en": "Dew point Changed"
            },
            "tokens": [
                {
                    "name": "value",
                    "title": {
                        "en": "Dew point"
                    },
                    "type": "number",
                    "example": 3
                }
            ]
        },
        {
            "id": "measure_temperature.dewPoint_is_less",
            "title": {
                "en": "The dew point becomes less than"
            },
            "titleFormatted": {
                "en": "The dew point becomes less than [[value]]°C"
            },
            "tokens": [
                {
                    "name": "value",
                    "title": {
                        "en": "Dew point"
                    },
                    "type": "number",
                    "example": 3
                }
            ],
            "args": [
                {
                    "type": "number",
                    "name": "value",
                    "min": -40,
                    "max": 70,
                    "step": 1,
                    "placeholder": {
                        "en": "Set a value"
                    },
                    "title": {
                        "en": "Dew point"
                    }
                }
            ]
        },
        {
            "id": "measure_temperature.dewPoint_is_greater",
            "title": {
                "en": "The dew point becomes greater than"
            },
            "titleFormatted": {
                "en": "The dew point becomes greater than [[value]]°C"
            },
            "tokens": [
                {
                    "name": "value",
                    "title": {
                        "en": "Dew point"
                    },
                    "type": "number",
                    "units": "°C",
                    "example": 3
                }
            ],
            "args": [
                {
                    "type": "number",
                    "name": "value",
                    "min": -40,
                    "max": 70,
                    "step": 1,
                    "placeholder": {
                        "en": "Set a value"
                    },
                    "title": {
                        "en": "Lightning strikes"
                    }
                }
            ]
        }
    ],

```

I am then setting the value with:
` await this.setCapabilityValue('measure_temperature.dewPoint', dewPoint);`

I setup a flow to trigger when the Dew point changes but it is never fired.

The full code I am using it located at https://github.com/AdyRock/com.misol/tree/Automatic-Trigger-Issue

**Comment by tjallingt** [comment] 2021-06-02 13:03
Sorry that responding took a while, this appears to be a "bug" in our documentation. The name of the token shouldn't be `"value"` but `"measure_temperature.dewPoint"`. Can you test whether that works for you? Then I'll make sure the documentation is updated to explain the correct token name.

**Comment by AdyRock** [comment] 2021-06-02 14:56
Using "measure_temperature.dewPoint" works.
Is there a similar technique for the new "is greater than" and "is less than" triggers?

**Comment by tjallingt** [comment] 2021-06-02 15:04
Great to hear that fixes the flow cards.
~I believe greater than and less than are supposed to be postfixed with `_threshold_above` and `_threshold_below`. Those still need documentation.~

The "capability threshold flow cards" don't support a token right now. Not sure what the reason is, I think it would be possible to add tokens but I'll need to discuss that internally.

**Comment by AdyRock** [comment] 2021-06-02 15:07
Great, I shall try them out.
Also on the page https://apps.developer.homey.app/the-basics/devices/capabilities#using-the-same-capability-more-than-once could you add a linh to the https://apps.developer.homey.app/the-basics/devices/capabilities#using-the-same-capability-more-than-once page. At the moment if you are looking at the capabilities page then it not apparent that the sub capabilities features exists.

**Comment by tjallingt** [comment] 2021-06-02 15:10
Oh wait that doesn't need documentation, you shouldn't need to add `_threshold_above` and `_threshold_below` flow cards.
Those flow cards are generated and added automatically for all `measure_` and `meter_` capabilities.

**Comment by AdyRock** [comment] 2021-06-02 15:12
But does that include sub capabilities?

**Comment by tjallingt** [comment] 2021-06-02 15:14
It should, if it doesn't add them for your sub-capabilities that'd be a bug.

**Comment by AdyRock** [comment] 2021-06-02 15:16
OK, I will remove mine and see if the automatic one kick in.

**Comment by AdyRock** [comment] 2021-06-02 15:22
I have removed my definitions for greater and less than triggers and they have disappeared as options to select but the automatic ones haven't appeared.
I have the ones for measure_temperature but not for measure_temperature.dewPoint

**Comment by tjallingt** [comment] 2021-06-02 15:52
That seems like a bug, I'll try to reproduce tomorrow and see whether that's intended behaviour or not.

**Comment by tjallingt** [comment] 2021-06-03 07:30
Oh, sorry Flow Cards are indeed not generated for sub-capabilities at the moment as mentioned in the "warning box" here: https://apps.developer.homey.app/the-basics/devices/capabilities#using-the-same-capability-more-than-once

We may re-evaluate that decision though

**Comment by tjallingt** [comment] 2021-06-03 07:39
Closing because the documentation has been updated, the generated Flow Cards for sub-capabilities are expected behaviour but feel free to make another issue as a feature request :)

**Closed as completed by tjallingt** 2021-06-03 07:39 UTC
Labels: bug, docs
