### ISSUE TITLE
Stack trace not providing much info in relation to unhandled rejection crash report

### ISSUE THREAD

**Issue by PeterEIER** [athombv/apps-sdk-issues#251] opened 2022-05-23 11:36 UTC
I receive these 2 stack traces, but these do not provide me with the information I need to fix the issue. To fix them I need to know the name of the non existing capabilty or were in my code the error occurs, neither is provided in the stack trace. So these stack traces are completely useless to me.

![8FA9225D-1CD9-426A-BC1A-7DB15BAA2F80](https://user-images.githubusercontent.com/25422313/169809445-98ae7020-421d-4584-b84f-c9cf5b65e264.jpeg)
![69BABA5D-E4FC-49DC-8131-0DC3ACD080FA](https://user-images.githubusercontent.com/25422313/169809452-1d57da28-5cac-4f4d-871c-95c343c6ae99.jpeg)

**Comment by RobinBol** [comment] 2022-05-25 14:12
Hi @PeterEIER, thanks for reporting your issue. We will take a look at how we can improve this. Will get back to you!

**Comment by RobinBol** [comment] 2022-06-08 12:39
@PeterEIER Homey Pro v7.4.2 will improve this error message to include the capability id of the invalid capability, hopefully this will help you debugging this issue.

**Comment by RobinBol** [comment] 2022-06-13 13:55
@PeterEIER Homey Pro v7.4.2-rc.4 is now available in the Experimental channel. I will consider this issue resolved for now, but please feel free to continue the discussion here if necessary.

**Comment by PeterEIER** [comment] 2022-06-23 19:52
![7080A499-B240-405E-A454-D3536A9AA493](https://user-images.githubusercontent.com/25422313/175385467-f1d45d5d-0d97-4f7b-973a-618b74b353c8.jpeg)

stack trace from 7.4.2, nothing has changed or what did I miss?

**Comment by RobinBol** [comment] 2022-06-24 06:59
Ah I see, this error originates elsewhere, will see if we can fix it there as well.

**Comment by RobinBol** [comment] 2022-07-06 11:56
@PeterEIER Homey v8.0.2 should fix this!

**Comment by h3rman** [comment] 2022-07-08 16:30
I also got an error where the stack trace doesn't help. Homey v8.0.2

`Error: dim InvalidTypeError: undefined is undefined but expected number (invalid_type)`

![image](https://user-images.githubusercontent.com/1621579/178031411-d2b55940-98bf-4f60-afb6-f868f3a37c50.png)

**Comment by PeterEIER** [comment] 2022-07-09 14:24
@RobinBol well it indeed now differentiates to the extended that I know the capability name. Now it turns out that all my custom capabilities are flagged as invalid (i.e. "Error: Invalid Capability: fan_rate"). Based on the fact that the info provided by the stack trace is for all the errors the same I do guess the crash occurs in the same line of code. However with the provided information it is still impossible to pin point the location / line of code were things go wrong.

**Comment by PeterEIER** [comment] 2022-07-10 16:28
@RobinBol and I like to add to the above, so far I was not able to reproduce the error… not a single crash report shows up when I myself use the app (which I do on daily basis). Puzzled…

**Comment by RobinBol** [comment] 2022-07-12 08:22
> I also got an error where the stack trace doesn't help. Homey v8.0.2
> 
> `Error: dim InvalidTypeError: undefined is undefined but expected number (invalid_type)`

You should be looking for a line of code in your app setting the dim capability value to anything other then a number.


> @RobinBol well it indeed now differentiates to the extended that I know the capability name. Now it turns out that all my custom capabilities are flagged as invalid (i.e. "Error: Invalid Capability: fan_rate"). Based on the fact that the info provided by the stack trace is for all the errors the same I do guess the crash occurs in the same line of code. However with the provided information it is still impossible to pin point the location / line of code were things go wrong.

How did you add the custom capabilities? It might be that older devices were initially paired without that custom capability that you added later, the could explain why you can not reproduce (as you are pairing on the current app version).

**Comment by WeeJeWel** [comment] 2022-07-12 09:09
Tip:

```js
// Device.js
if(this.hasCapability('my_custom_capability') ) {
  this.setCapabilityValue('my_custom_capability', 123).catch(this.error);
}
```

**Comment by PeterEIER** [comment] 2022-07-12 17:21
Thx for the tip @WeeJeWel, did you copied it from my code 😎 as this is exactly how my code looks like… and this unfortunately does not catch anything 🤷🏼‍♂️

**Comment by PeterEIER** [comment] 2022-07-12 17:26
> How did you add the custom capabilities? It might be that older devices were initially paired without that custom capability that you added later, the could explain why you can not reproduce (as you are pairing on the current app version).

These custom capabilities do exist since the birth of my app over 4 years ago. When a users adds the airco device these custom capabilities are created.

**Comment by RobinBol** [comment] 2022-07-13 06:57
@PeterEIER is the source code freely available somewhere? Maybe I could take a quick look.

**Comment by PeterEIER** [comment] 2022-07-13 08:22
@RobinBol sure have a look at my GitHub repository.

**Comment by RobinBol** [comment] 2022-07-13 11:50
> Thx for the tip @WeeJeWel, did you copied it from my code 😎 as this is exactly how my code looks like… and this unfortunately does not catch anything 🤷🏼‍♂️

1) Actually, this is not the case. I've found a number of places where `setCapabilityValue("fan_rate", x)` is called without checking `hasCapability()` before hand.

2) Besides, I see you are heavily using `removeCapability()` and `addCapability()`, which is not really recommendend. These are expensive methods that have some unwanted side effects. Generally you only want to use this for migration purposes once. What you are doing on repair is possible (if the migration checks are solid), but, more importantly, these add/remove capabilities are asynchronous methods, you should await each one of these before doing anything else with the device, especially adding/removing even more capabilities.

Point 1 in combination with 2 is most likely to be your problem.

**Comment by PeterEIER** [comment] 2022-07-13 13:27
@RobinBol thx for the advice.

1. Check, the #has capability() I do not use I will add the check.

2. Regarding the #removeCapabilty() code, that is no longer needed anyhow it was used/needed for migration from 5 airco drivers to just 2 airco drivers many a years ago.

**Comment by RobinBol** [comment] 2022-07-13 13:29
Alright! I'll close this issue for now as the initial problem seems to be resolved. If not, please leave a comment to re-open.

**Closed as completed by RobinBol** 2022-07-13 13:29 UTC
