### ISSUE TITLE
[Z-wave] No compatible app found - added as Basic Z-wave device -  still all capabilities of selected device shown in app

### ISSUE THREAD

**Issue by TedTolboom** [athombv/apps-sdk-issues#60] opened 2019-02-17 08:09 UTC
When trying to add a Z-wave device which has ID's not available in any of the apps, it should be added as a Basic Z-wave device with not capabilities / settings etc.

When using the "choose a device" option, the inclusion will result in the correct error (added as Basic device):
![img_2001](https://user-images.githubusercontent.com/17163431/52910109-f9daf080-3292-11e9-88a3-396212b380bf.PNG)

However, the device icon / capabilities and even settings are inherited from the device that was selected in the "choose a device" option... for "demonstration purpose" the Fibaro Motion sensor was used, see below screenshots for reference:
![img_2002](https://user-images.githubusercontent.com/17163431/52910153-9a311500-3293-11e9-9ddd-c20f1fdf8949.PNG)
![img_2003](https://user-images.githubusercontent.com/17163431/52910154-9a311500-3293-11e9-8625-d74fa072596e.PNG)
![img_2004](https://user-images.githubusercontent.com/17163431/52910155-9ac9ab80-3293-11e9-8fab-47268cc89582.PNG)
![img_2005](https://user-images.githubusercontent.com/17163431/52910156-9ac9ab80-3293-11e9-909f-972efd0b5512.PNG)

In this example, I used a relay device not having any of these options ;-)

**Comment by mapulu** [comment] 2019-02-19 09:13
I would call it a feature not a bug.

**Comment by WeeJeWel** [comment] 2019-02-26 17:04
Fixed in Homey v2.0.5. Thank you for reporting.

**Closed as completed by WeeJeWel** 2019-02-26 17:04 UTC
