### ISSUE TITLE
Need pollInterval to feedback status on ZigBee Device

### ISSUE THREAD

**Issue by kevinhab** [athombv/apps-sdk-issues#40] opened 2019-01-21 09:15 UTC
Hi All,
I 'm build an app for ZigBee Device.
If it want to update status from ZigBee Device, it must have **pollInterval** function (don't have pollInterval function, no feedback status ZigBee Device)
Example code:
`const ZigBeeDevice = require('homey-meshdriver').ZigBeeDevice;`

`class WallSwitch2 extends ZigBeeDevice {`

	async onMeshInit() {

		// Register onoff.1 capability
		this.registerCapability('onoff.1', 'genOnOff', {
			getOpts: {
				getOnStart: true,
				pollInterval: 2000,
			},
			endpoint: 0
		});
		
		// Register onoff.2 capability
		this.registerCapability('onoff.2', 'genOnOff', {
			getOpts: {
				getOnStart: true,
				pollInterval: 2100,
			},
			endpoint: 2
		});
	}
}

`module.exports = WallSwitch2;`

But insert **pollInterval** function, it'll make app slowly or unstable when there are many ZigBee devices.
Could anyone please fix this issue?

**Comment by WeeJeWel** [comment] 2019-02-26 17:05
Duplicate of https://github.com/athombv/node-homey-meshdriver/issues/123

**Closed as completed by WeeJeWel** 2019-02-26 17:05 UTC
