### ISSUE TITLE
Access to https://apps.athom.com/developer/dashboard denied

### ISSUE THREAD

**Issue by holkerveen** [athombv/apps-sdk-issues#3] opened 2018-12-06 20:58 UTC
Hi! I got a 403 error on `https://apps.athom.com/developer/dashboard`, and got redirected to `https://apps.athom.com/unauthorized?origin=https:%2F%2Fapps.athom.com%2Fdeveloper%2Fdashboard`.

Of course I was logged in at the time, and signing in via the provided link does not work. I got here by clicking on `My Apps` in `https://developer.athom.com/`

**Comment by WeeJeWel** [comment] 2018-12-14 16:47
I cannot reproduce this issue. Closing this until someone else has the same issue.

**Comment by holkerveen** [comment] 2018-12-15 11:13
Oh, okay. That seems very unlikely, because it behaves that way on all my devices. It does not matter if I disable caches, turn on anonymus browsing/incognito mode, anything.

I cannot find any redirect headers or 302 status codes so it seems like a Javascript redirect. Also, I do see some flash of a dashboard before it redirects. Going through what I can see, It seems to redirect in a $stateChangeStart event handler, I believe toState.data.hasAccess(user) should return true there but it returns `undefined` in my case. See screenshot with breakpoints below.

That's all I can see at this time. I should also note I am running home on 2.0 firmware (rc3 as of yet).

How can I help tracing the problem? I would like to create some coolness but I cannot do anything fun right now :-(
![afbeelding](https://user-images.githubusercontent.com/11218586/50042415-b54c9200-0062-11e9-84fa-fc3fde9485a1.png)

**Comment by WeeJeWel** [comment] 2018-12-20 12:03
I think this happens because you haven't submitted your first app yet... does https://apps.athom.com/developers work for you?

**Comment by SailingDuck** [comment] 2018-12-20 14:03
Get the same redirect with this page:
![image](https://user-images.githubusercontent.com/23644634/50289172-558e2680-0468-11e9-9914-d625e258dc9b.png)
(signing in doesn't work)

https://apps.athom.com/developers is working for me

**Comment by WeeJeWel** [comment] 2018-12-20 14:14
`(signing in doesn't work)`

Please elaborate?

**Comment by SailingDuck** [comment] 2018-12-20 14:48
The sign in button could imply I'm not logged. Signing in again gives the same result.

**Comment by Dijker** [comment] 2018-12-20 17:18
I tried here from incognito letting the https://developer.athom.com/ linkt redirect me to  https://apps.athom.com/developers ....
Tried not loged in  and may developer account.
Almost gave up.

Incognito Window open https://developer.athom.com/ 
Log in with Athom -NON-Developer- Account 
klik left column My Apps => that one opens https://apps.athom.com/developer/dashboard logged in to the store but gives the error @SailingDuck  gives.... 

For me the rest nothing strange ;-)

**Comment by WeeJeWel** [comment] 2019-01-02 17:08
Changed the link to https://apps.athom.com/search?author=$userid

**Closed as completed by WeeJeWel** 2019-01-02 17:08 UTC
