### ISSUE TITLE
BLE discovery gives 0 advertisements

### ISSUE THREAD

**Issue by koktaildotcom** [athombv/apps-sdk-issues#202] opened 2021-04-29 15:30 UTC
Homey firmware: Homey v6.1.0-rc.2
Scenario: https://github.com/koktaildotcom/com.beacon/tree/feature/specific-beacon-detection

When calling `const advertisements = await this.homey.ble.discover([]);` the first result (when cache is cold) results in all discoverable devices.

However when you wait 10 seconds and try to run the discovery once again it give sometimes an empty array.

**Comment by mrlukasbos** [comment] 2021-04-29 18:18
That seems like a bug.

However, I cannot reproduce the issue right away. Unfortunately I can't access your link, however, I'd like to see the code you use. Do you apply a service filter?

**Comment by koktaildotcom** [comment] 2021-04-29 19:15
Sorry, I merged the branch with master: 
https://github.com/koktaildotcom/com.beacon

I don't use a service filter in the code. You could make a simple test script with timeout.

Pseudo:
setTimeout(
console.log((await this.homey.ble.discover([])).length)
,10000)

**Comment by koktaildotcom** [comment] 2021-04-30 07:13
I've made a simple reproduction script inside the app.js in branch: https://github.com/koktaildotcom/com.beacon/tree/issue/BLE-discovery-gives-no-advertisements




      async onInit() {
  
          console.log(await this.getAmountOfBleAdvertisements())
  
          setTimeout(async () => {
              console.log(await this.getAmountOfBleAdvertisements())
          },10000)
  
          setTimeout(async () => {
              console.log(await this.getAmountOfBleAdvertisements())
          },20000)
  
          setTimeout(async () => {
              console.log(await this.getAmountOfBleAdvertisements())
          },30000)
  
          setTimeout(async () => {
              console.log(await this.getAmountOfBleAdvertisements())
          },40000)
  
          setTimeout(async () => {
              console.log(await this.getAmountOfBleAdvertisements())
          },50000)
      }
  
      async getAmountOfBleAdvertisements() {
          return `The amount of found advertisements is: ${(await this.homey.ble.discover([])).length}`
      }

**Comment by mrlukasbos** [comment] 2021-04-30 08:05
Thank you for reporting. I have indeed managed to reproduce the issue with this approach. I will notify you in this thread when a fix is available.

**Comment by koktaildotcom** [comment] 2021-05-08 20:04
Is there any progress in this issue? The beacon app is dependent on this working as expecting. I got a lot of questions about this.

**Comment by mrlukasbos** [comment] 2021-05-10 09:34
Yes, the issue has been found and fixed. However, it first will be rolled out to our experimental channels, so it may take some time before it will reach the stable channel.

**Comment by koktaildotcom** [comment] 2021-05-10 09:50
Great news! Thanks for fixing the issue!

**Comment by RobinBol** [comment] 2021-05-27 16:38
@koktaildotcom the fix has been released in the Experimental channel (Homey v7.0.0).

**Comment by zwaardemaker** [comment] 2021-05-27 17:17
False alarms are still there after the fix.

**Comment by mrlukasbos** [comment] 2021-05-28 11:06
I don't understand what you mean exactly. This specific issue is about advertisements not being found. What kind of "false alarms" are you referring to?

**Comment by zwaardemaker** [comment] 2021-05-28 11:26
One of the app devolpers just explained it to me. So you can ignore my post.Best regards,PeterOp 28 mei 2021 13:06 schreef Lukas Bos ***@***.***>:
I don't understand what you mean exactly. This specific issue is about advertisements not being found. What kind of "false alarms" are you referring to?

**Comment by mrlukasbos** [comment] 2021-05-28 11:28
Ah, no problem. Thanks for the clarification 😄

**Comment by RobinBol** [comment] 2021-06-14 11:09
Closing this issue since the fix has been released in Homey v7.0.0, currently stable.

**Closed as completed by RobinBol** 2021-06-14 11:09 UTC
Labels: bug, ble
