### ISSUE TITLE
Alert State not shown on widgets

### ISSUE THREAD

**Issue by MadMonkey87** [athombv/apps-sdk-issues#189] opened 2021-04-06 11:53 UTC
Hi

Some users reported a strange behaviour of my DeConz app and I think this might be an Homey issue after all. The problem affects devices with the alarm_motion or the alarm_contact capability. On the dashboard no activity is shown but if you go to the device details you can see that the alarm has been triggered properly. 

I think this most likely is a problem of homey itself because of the following reasons:
- as developer we cannot directly set the alarm indicator, only the alarm capability and this seems to work fine and also gets displayed in the homey ui in the device details
- it only affects devices that are added recently. Devices that were added earlier on do not have this problem
- Reverting back to older app versions that were used to add the working devices earlier on show exactly the same behaviour -> clear indicator it is not the app
- the working and the non-working devices look exactly the same trough the api, have the same capabilities, same driver

Some hint's & thoughts that might be relevant to sovle the riddle:
- not sure but could be related: maybe everything was okay on homey 4.x but the problem came with 5.x?
- the app runs just fine on homey 5.x but it is still built for sdk v2 and compatiblity >=4.0.0 -> should however not be a problem

Detail page shows the alert properly: https://user-images.githubusercontent.com/71789877/112967960-17eecc80-914c-11eb-8f65-2a0300d22051.png

But the widget does not: https://user-images.githubusercontent.com/71789877/112967899-09081a00-914c-11eb-95a7-1818b4fcbc43.png

Here is how it should look:
https://user-images.githubusercontent.com/71789877/112967995-2210cb00-914c-11eb-8e08-1c186a4604a2.png

**Comment by jeroenwienk** [comment] 2021-04-07 09:04
Hi,

Thank you for reporting this issue. It seems our frontends base the display of the indicator on a device with class `sensor` and any capability that starts with `alarm_`. I've put it up for discussion and will get back to you shortly.

**Comment by jeroenwienk** [comment] 2021-04-09 09:36
We will remove the class check for indicator sensor and base them on any `alarm_` capability.

**Comment by iisworks** [comment] 2021-04-21 05:11
@jeroenwienk Will a fix for this be released in the FW 6 beta?

**Comment by jeroenwienk** [comment] 2021-04-21 08:03
> @jeroenwienk Will a fix for this be released in the FW 6 beta?

This is not a firmware release but a web app and mobile app release. It has since been fixed in the web app and the mobile app fix should be live soon.

**Comment by iisworks** [comment] 2021-04-21 09:25
Thanks, confirmed in the WebApp!

**Closed as completed** 2021-05-14 15:00 UTC
Labels: bug, waiting on release
