### ISSUE TITLE
await BleCharacteristic.discoverDescriptors() struck

### ISSUE THREAD

**Issue by KrakenTyio** [athombv/apps-sdk-issues#99] opened 2019-10-21 15:12 UTC
Im not able obtain `BleDescriptor` from `await BleCharacteristic.discoverDescriptors()`, it always stuck.

Also when im debugging with node inspector, its never go through this command and stoped on 60 second timeout of not interacting with BlePeripheral.

**Comment by mrlukasbos** [comment] 2021-04-13 07:15
Hi KrakenTyio,

Sorry for the long silence. Many BLE issues have been resolved in Homey v6.0.0 which is currently available as an experimental release. I could not reproduce the issue that you describe above. However, there were indeed some other issues with descriptors which have been fixed which may fix your issue as well. 

I will be closing this issue due to it's age but feel free to reopen/respond/open a new issue if you want.

**Closed as completed by mrlukasbos** 2021-04-13 07:15 UTC
Labels: ble
