### ISSUE TITLE
setStoreValue seems to block my entire Homey mobile app.

### ISSUE THREAD

**Issue by kjeet90** [athombv/apps-sdk-issues#236] opened 2021-11-23 09:27 UTC
When I'm using setStoreValue it seems to block my entire Homey mobile app.

I have created a example app ([Github repo](https://github.com/kjeet90/store-interval)) to reproduce the issue. If I add the device from this app the issue occurs. If I remove it again everything is just fine. The only thing this device does is to write two values to the store on a fixed interval of 5 seconds.

The easiest way of seeing the issue is to just navigate back and forth in a devices' settings and it will then block/lag for a while before it continues.

[Here is a video](https://drive.google.com/file/d/1531DHcpSSVuuHR70XTVfPKhY_kxq52wZ/view?usp=sharing) where I first have that  device installed, and you can see that it is blocking/lagging when I am going back and forth in the settings of another apps device (Virtual Devices). I then remove the device which is writing to the store on the fixed interval, and then do the same back and forth in the settings of the Virtual Device where you can see that there is no blocking/lagging anymore.

Another Homey user suggested that it could be just my local store having issues, since he was unable to reproduce it. If that is the case is there anything I can do to fix my store?

**Comment by tjallingt** [comment] 2021-11-23 09:35
Thanks for reporting, just from the description I would guess something else is going on since `setStoreValue` should not cause updates on the front-end. However it is possible there is a bug somewhere causing this behaviour.
The reproduction app is great! I'll take a look and see if I can reproduce the issue and figure out whats happening.

**Comment by tjallingt** [comment] 2021-11-24 14:20
Yea so I confirmed that updating the store sends an update to the front-end which is not necessary. Also the smartphone app likely rerenders when a device update event is received so the combination of those issues may explain the behaviour you are seeing.

We will fix the device update event we are accidentally emitting, that should be released as part of Homey 7.3.0.

You can probably still trigger this issue using other updates (such as capability values). Changing how/when the smartphone app renders device updates is a bigger project. We are planning to improve that but I hope you will understand that it might take a while :)

I will close this issue now, if you have further remarks or questions I can open the issue again.

**Closed as completed by tjallingt** 2021-11-24 14:20 UTC

**Comment by kjeet90** [comment] 2021-11-24 14:26
So when 7.3.0 is released the "blocking" when writing to the store will be resolved? That is the only time I've noticed it, so if that will be fixed I will be a happy man!

**Comment by tjallingt** [comment] 2021-11-24 14:33
Yea I believe so, if not please create another issue or comment on this one :)
