### ISSUE TITLE
Flow condition card "Day number is between" incorrect behavior

### ISSUE THREAD

**Issue by runely** [athombv/apps-sdk-issues#160] opened 2020-12-28 10:31 UTC
The flow condition card `Day number is between` has incorrect behavior when second day number is lower than first day number.

The description in the flow card states `When the second day number is earlier than the first day number, it is considered to be next month`

Today the day number is 28, and the month is 12. So the next month will be 1 in the next year.

When i put in `23` for the *first day number* and `3` for the *second day number* i get a red stop sign when testing the flow!

Homey firmware: 4.2.0

**Comment by mrlukasbos** [comment] 2021-01-13 14:41
Thanks for reporting the issue. The issue is resolved in the upcoming Homey 5.0.0.

**Closed as completed by mrlukasbos** 2021-01-13 14:41 UTC
